{{- if (and (.Values.browser.enabled) (not .Values.testing)  (.Values.docServer.enabled))}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: browser-{{ .Release.Name }}
spec:
  replicas: {{.Values.browser.replicaCount}}
  selector:
    matchLabels:
      app: browser-{{ .Release.Name }}
  template:
    metadata:
      labels:
        app: browser-{{ .Release.Name }}
    spec:
      containers:
        - name: browser
          image: {{ .Values.browser.image.name }}:{{ .Values.browser.image.tag }}
          ports:
          - containerPort: 8080
          env:
            - name: SB_catalogUrl
              value: "/stac"
            - name: SB_prefixPath
              value: "/browser"
---
apiVersion: v1
kind: Service
metadata:
  name: browser-{{ .Release.Name }}
spec:
  selector:
    app: browser-{{ .Release.Name }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
# We need a separate ingress because browser does not play well with nginx rewrite_path directive
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stac-browser-ingress
spec:
  {{- if (and (.Values.ingress.className) (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion)) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    - http:
        paths:
        - pathType: Prefix
          path: "/browser"
          backend:
            service:
              name: browser-{{ $.Release.Name }}
              port:
                number: 8080

{{- end }}